update (#6)
* update pipeline and fix smoke tests

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,92 +1,114 @@
 #!/bin/sh -e
 
-DOCKER_USERNAME=${DOCKER_USERNAME:-vallyian}
-DOCKER_REPO=${DOCKER_REPO:-media-share}
-PLATFORMS=linux/amd64,linux/arm64/v8 # linux/arm/v7,linux/ppc64le,linux/s390x
+docker_username="${DOCKER_USERNAME:-vallyian}"
+docker_repo="${DOCKER_REPO:-media-share}"
+github_main="${GITHUB_MAIN:-false}"
+new_version="${NEW_VERSION}"
+github_sha="${GITHUB_SHA}"
+semver="${SEMVER:-0.0.0}"
+npm_audit_level="${NPM_AUDIT_LEVEL:-low}"
+trivy_severity="${TRIVY_SEVERITY:-UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL}"
+artifacts_dir="${PWD}/artifacts"
 
-github_env() {
-    echo "::set-output name=GITHUB_MAIN::${GITHUB_MAIN}"
-}
+main() { case "${1}" in
+    "semver"  ) semver  ;;
+    "build"   ) build   ;;
+    "test"    ) test    ;;
+    "scan"    ) scan    ;;
+    "results" ) results ;;
+    "push"    ) push    ;;
 
-calc_semver() {
-    if [ "${GITHUB_MAIN}" = "true" ]; then
-        echo "SEMVER: ${SEMVER}"
-        echo "::set-output name=SEMVER::${SEMVER}"
+    *) term "USAGE:   ./run   semver | build | test | results | scan | push"
+esac }
+term() { echo "\033[0;31m${1}\033[0m"; exit 1; }
+
+####################################################################################################
+
+semver() {
+    [ "${new_version}" != "" ] || term "semver can only run in CI"
+
+    if [ "${github_main}" = "true" ]; then
+        echo "::set-output name=SEMVER::${new_version}"
+        echo "SEMVER: ${new_version}"
     else
-        echo "SEMVER: ${SEMVER}-${GITHUB_SHA}"
-        echo "::set-output name=SEMVER::${SEMVER}-${GITHUB_SHA}"
+        echo "::set-output name=SEMVER::${new_version}-${github_sha}"
+        echo "SEMVER: ${new_version}-${github_sha}"
     fi
 }
 
 build() {
-    rm -rf artifacts \
-    || exit 1
+    rm -rf artifacts
 
     docker buildx build \
-        --pull \
+        `[ ${github_sha} = "" ] || echo --pull` \
         --target export \
         --output=type=local,dest=artifacts \
-        . \
-    || exit 1
+        .
 
     docker buildx build \
-        -t ${DOCKER_USERNAME}/${DOCKER_REPO}:local \
-        --build-arg SEMVER \
-        --pull \
+        -t ${docker_username}/${docker_repo}:${semver} \
+        --build-arg "NPM_AUDIT_LEVEL=${npm_audit_level}" \
+        --build-arg "SEMVER=${semver}" \
+        `[ ${github_sha} = "" ] || echo --pull` \
         --output=type=docker \
-        . \
-    || exit 2
+        .
 
-    docker image inspect ${DOCKER_USERNAME}/${DOCKER_REPO}:local > /dev/null \
-    || exit 3
+    docker image inspect ${docker_username}/${docker_repo}:${semver} > /dev/null
 }
 
-test_end_to_end() {
-    local container=${DOCKER_USERNAME}-${DOCKER_REPO}-local
+test() {
+    local container=${docker_username}-${docker_repo}-${semver}-smoke-test
+    local smoke_test_dir="${artifacts_dir}/smoke-test"
+    local cert_crt="${smoke_test_dir}/cert.crt"
+    local cert_key="${smoke_test_dir}/cert.key"
+    local media_dir="${smoke_test_dir}/test-dir"
+    local curl_output="${smoke_test_dir}/curl-output.txt"
+    local container_logs="${smoke_test_dir}/container-logs.txt"
+    local test_failed=true
 
-    if [ ! -f server/certs/cert.crt ] || [ ! -f server/certs/cert.key ]; then
-        mkdir -p server/certs
-        openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 \
-            -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" \
-            -out server/certs/cert.crt -keyout server/certs/cert.key
-    fi
+    rm -rf "${smoke_test_dir}"
+    mkdir -p "${media_dir}"
+    echo "test file" > "${media_dir}/test-file"
 
-    if [ ! -f server/media/test-dir/test-file ]; then
-        mkdir -p server/media/test-dir
-        echo "test file" > server/media/test-dir/test-file
-    fi
+    echo "creating test self-signed certs..."
+    openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 \
+        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" \
+        -out "${cert_crt}" -keyout "${cert_key}"
+    chmod 777 "${cert_crt}" "${cert_key}"
 
+    echo "starting service..."
     (docker stop ${container} && docker rm ${container} || echo "container ${container} not running") && \
-    docker run --name ${container} --rm --detach \
-        -v "${PWD}/server/media:/home/node/app/media" \
-        -v "${PWD}/server/certs/cert.crt:/run/secrets/cert.crt:ro" \
-        -v "${PWD}/server/certs/cert.key:/run/secrets/cert.key:ro" \
+    docker run --name ${container} --rm \
+        -v "${smoke_test_dir}:/home/node/app/media" \
+        -v "${cert_crt}:/run/secrets/cert.crt:ro" \
+        -v "${cert_key}:/run/secrets/cert.key:ro" \
+        -e "DEBUG=*" \
         -e "G_CLIENT_ID=test.apps.googleusercontent.com" \
         -e "G_EMAILS=test@gmail.com" \
         -p "58081:58082" \
-        ${DOCKER_USERNAME}/${DOCKER_REPO}:local
+        ${docker_username}/${docker_repo}:${semver} &
 
-    timeout 25s bash -c 'while [[ "$(curl --insecure https://localhost:58081/health)" != "healthy" ]]; do sleep 5; done'
+    echo "waiting for service to become available..."
+    timeout 30s bash -c 'while [[ "$(curl --insecure https://localhost:58081/health)" != "healthy" ]]; do sleep 5; done' \
+    || echo "health endpoint not available"
 
-    local http_result="server/test-results/e2e_test_run"
-    mkdir -p server/test-results
-    rm -rf server/test-results/e2e_test_run
-    curl --insecure --verbose https://localhost:58081/test-dir/test-file > "${http_result}" 2>&1
+    curl --insecure --verbose https://localhost:58081/test-dir >> "${curl_output}" 2>&1 \
+    || echo "test index media dir not available"
 
-    if ! grep -q "GET \/test-dir\/test-file HTTP\/1.1"   "${http_result}" \
-    || ! grep -q "HTTP\/1.1 401 Unauthorized"          "${http_result}"; then
-        echo "invalid http response"
-        exit 1
-    fi
+    curl --insecure --verbose https://localhost:58081/test-dir/test-file >> "${curl_output}" 2>&1 \
+    || echo "test static media file not available"
 
-    docker stop ${container}
-}
+    if   grep -Fq "GET /test-dir HTTP/1.1"           "${curl_output}" \
+    &&   grep -Fq "GET /test-dir/test-file HTTP/1.1" "${curl_output}" \
+    &&   grep -Fq "HTTP/1.1 401 Unauthorized"        "${curl_output}" \
+    && ! grep -Fq "HTTP/1.1 200 OK"                  "${curl_output}" \
+    ;then test_failed=false; fi
 
-check_test_results() {
-    if [ ! -f artifacts/test-results/*.xml ]; then
-        echo "no test results found"
-        exit 1
-    fi
+    docker logs ${container} > "${container_logs}" 2>&1 || echo "docker logs cmd failed"
+    docker stop ${container} || echo "docker stop cmd failed"
+    rm -rf "${media_dir}"
+
+    [ "${test_failed}" = "false" ] || term "smoke test failed"
 }
 
 scan() {
@@ -99,30 +121,31 @@ scan() {
         aquasec/trivy \
             image \
                 --exit-code=1 \
-                ${DOCKER_USERNAME}/${DOCKER_REPO}:local \
-    || exit 1
+                --severity "${trivy_severity}" \
+                ${docker_username}/${docker_repo}:${semver}
+}
+
+results() {
+    local errors=""
+
+    [ ! -f ${artifacts_dir}/npm-test.fail    ] || errors="npm test failed\n${errors}"
+    # [ ! -f ${artifacts_dir}/npm-lint.fail    ] || errors="npm lint failed\n${errors}"
+    [   -f ${artifacts_dir}/unit-tests/*.xml ] || errors="npm test results not found\n${errors}"
+
+    [ "${errors}" = "" ] || term "${errors}"
 }
 
 push() {
+    [ "${semver}" != "0.0.0" ] || term "push can only run in CI"
+
     docker buildx build \
-        -t ${DOCKER_USERNAME}/${DOCKER_REPO}:${SEMVER} \
-        -t ${DOCKER_USERNAME}/${DOCKER_REPO}:latest \
-        --build-arg SEMVER \
-        --platform ${PLATFORMS} \
+        -t ${docker_username}/${docker_repo}:${semver} \
+        -t ${docker_username}/${docker_repo}:latest \
+        --build-arg "SEMVER=${semver}" \
+        --platform "linux/amd64,linux/arm64/v8" \
         --pull \
         --output=type=registry \
-        . \
-    || exit 1
+        .
 }
 
-case "${1}" in
-    "github-env"         ) github_env         ;;
-    "calc-semver"        ) calc_semver        ;;
-    "build"              ) build              ;;
-    "e2e"                ) test_end_to_end    ;;
-    "check-test-results" ) check_test_results ;;
-    "scan"               ) scan               ;;
-    "push"               ) push               ;;
-
-    *) echo "\033[0;31mUSAGE:   ./run   github-env | calc-semver | build | e2e | check-test-results | scan | push\033[0m" && exit 1
-esac
+main "$@"
