unauthorised render with status 401

diff --git a/run b/run
--- a/run
+++ b/run
@@ -44,59 +44,68 @@ build() {
     docker image inspect ${docker_username}/${docker_repo}:${semver} > /dev/null
 }
 
+test_result() {
+    curl --insecure --verbose https://localhost:58081${1} > "${2}" 2>&1 || return 1
+    grep -Fq "GET ${1} HTTP/1.1"         "${2}" || return 2
+    grep -Fq "HTTP/1.1 401 Unauthorized" "${2}" || return 3
+    return 0
+}
 test() {
     local container=${docker_username}-${docker_repo}-${semver}-smoke-test
     local smoke_test_dir="${artifacts_dir}/smoke-test"
-    local cert_crt="${smoke_test_dir}/cert.crt"
-    local cert_key="${smoke_test_dir}/cert.key"
-    local media_dir="${smoke_test_dir}/test-dir"
-    local curl_output="${smoke_test_dir}/curl-output.txt"
+    local media_share_dir="${smoke_test_dir}/media"
+    local media_certs_dir="${smoke_test_dir}/certs"
+    local cert_crt="${media_certs_dir}/cert.crt"
+    local cert_key="${media_certs_dir}/cert.key"
+    local media_test_dir="${media_share_dir}/test-dir"
     local container_logs="${smoke_test_dir}/container-logs.txt"
-    local test_failed=true
+    local test_failed=""
 
+    echo "removing smoke test data..."
     rm -rf "${smoke_test_dir}"
-    mkdir -p "${media_dir}"
-    echo "test file" > "${media_dir}/test-file"
+
+    echo "creating media test data..."
+    mkdir -p "${media_test_dir}"
+    echo "test file" > "${media_test_dir}/test-file"
 
     echo "creating test self-signed certs..."
+    mkdir -p "${media_certs_dir}"
     openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 \
-        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" \
+        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=127.0.0.1" \
         -out "${cert_crt}" -keyout "${cert_key}"
-    chmod 777 "${cert_crt}" "${cert_key}"
+
+    chmod -R 777 "${smoke_test_dir}"
 
     echo "starting service..."
-    (docker stop ${container} && docker rm ${container} || echo "container ${container} not running") && \
+    (docker stop ${container} > /dev/null 2>&1 && docker rm ${container} > /dev/null 2>&1) || echo "container ${container} not running"
     docker run --name ${container} --rm \
-        -v "${smoke_test_dir}:/home/node/app/media" \
-        -v "${cert_crt}:/run/secrets/cert.crt:ro" \
-        -v "${cert_key}:/run/secrets/cert.key:ro" \
-        -e "DEBUG=*" \
+        -p "58081:58082" \
+        -v "${media_share_dir}:/home/node/app/media" \
+        -v "${media_certs_dir}/cert.crt:/run/secrets/cert.crt:ro" \
+        -v "${media_certs_dir}/cert.key:/run/secrets/cert.key:ro" \
         -e "AUTH_CLIENT=test.apps.googleusercontent.com" \
         -e "AUTH_EMAILS=test@gmail.com" \
-        -p "58081:58082" \
+        -e "DEBUG=*" \
         ${docker_username}/${docker_repo}:${semver} &
 
-    echo "waiting for service to become available..."
-    timeout 30s bash -c 'while [[ "$(curl --insecure https://localhost:58081/health)" != "healthy" ]]; do sleep 5; done' \
-    || echo "health endpoint not available"
+    if timeout 30s sh -c 'while [ "$(curl --insecure https://localhost:58081/health)" != "healthy" ]; do sleep 5; done'; then
+        local requestId=1
+        test_result "/test-dir" "${smoke_test_dir}/curl-${requestId}.txt" || test_failed="${test_failed}${requestId},"
+        local test_result_code=$?
+        [ "${test_result_code}" = "0" ] || test_failed="${test_failed}${requestId},"
 
-    curl --insecure --verbose https://localhost:58081/test-dir >> "${curl_output}" 2>&1 \
-    || echo "test index media dir not available"
-
-    curl --insecure --verbose https://localhost:58081/test-dir/test-file >> "${curl_output}" 2>&1 \
-    || echo "test static media file not available"
-
-    if   grep -Fq "GET /test-dir HTTP/1.1"           "${curl_output}" \
-    &&   grep -Fq "GET /test-dir/test-file HTTP/1.1" "${curl_output}" \
-    &&   grep -Fq "HTTP/1.1 401 Unauthorized"        "${curl_output}" \
-    && ! grep -Fq "HTTP/1.1 200 OK"                  "${curl_output}" \
-    ;then test_failed=false; fi
+        local requestId=2
+        test_result "/test-dir/test-file" "${smoke_test_dir}/curl-${requestId}.txt" || test_failed="${test_failed}${requestId},"
+        local test_result_code=$?
+        [ "${test_result_code}" = "0" ] || test_failed="${test_failed}${requestId},"
+    else
+        echo "FAIL: GET /health - does not contain 'healthy'"
+    fi
 
     docker logs ${container} > "${container_logs}" 2>&1 || echo "docker logs cmd failed"
     docker stop ${container} || echo "docker stop cmd failed"
-    rm -rf "${media_dir}"
 
-    [ "${test_failed}" = "false" ] || term "smoke test failed"
+    [ "${test_failed}" = "" ] || term "smoke test (${test_failed}) failed"
 }
 
 scan() {
@@ -142,42 +151,49 @@ push() {
 
 dev() {
     [ -f "./server/.env" ] && export $(echo $(cat "./server/.env" | sed 's/#.*//g'| xargs) | envsubst)
-    [ -d "${MEDIA_SHARE_DIR}" ] || term "missing env var MEDIA_SHARE_DIR"
-    [ -d "${MEDIA_CERTS_DIR}" ] || term "missing env var MEDIA_CERTS_DIR"
+    [ "${MEDIA_SHARE_DIR}" = "" ] && term "missing env var MEDIA_SHARE_DIR"
+    [ -d "${MEDIA_SHARE_DIR}" ] || term "dir \"${MEDIA_SHARE_DIR}\" not found"
     [ "${AUTH_CLIENT}" = "" ] && term "missing env var AUTH_CLIENT"
     [ "${AUTH_EMAILS}" = "" ] && term "missing env var AUTH_EMAILS"
-    build
-    docker stop media-share-0.0.0 > /dev/null || echo "container not running"
-    docker stop media-share-0.0.0 > /dev/null || echo "container not found"
 
-    docker run --name media-share-0.0.0 --rm \
+    build
+
+    local container=${docker_repo}-${semver}
+
+    docker stop ${container} > /dev/null && docker rm ${container} > /dev/null || echo "container ${container} not running"
+    docker run --name ${container} --rm \
         -p "127.0.0.1:58081:58082" \
         -v "${MEDIA_SHARE_DIR}:/home/node/app/media" \
-        -v "${MEDIA_CERTS_DIR}/cert.crt:/run/secrets/cert.crt:ro" \
-        -v "${MEDIA_CERTS_DIR}/cert.key:/run/secrets/cert.key:ro" \
+        $([ "${MEDIA_CERTS_DIR}" != "" ] && [ -d "${MEDIA_CERTS_DIR}" ] && echo -v "${MEDIA_CERTS_DIR}/cert.crt:/run/secrets/cert.crt:ro") \
+        $([ "${MEDIA_CERTS_DIR}" != "" ] && [ -d "${MEDIA_CERTS_DIR}" ] && echo -v "${MEDIA_CERTS_DIR}/cert.key:/run/secrets/cert.key:ro") \
         -e "NODE_ENV=development" \
         -e "AUTH_CLIENT" \
         -e "AUTH_EMAILS" \
         -e "COOKIE_PASS" \
         -e "TOKEN_KEY" \
-        vallyian/media-share:0.0.0
+        ${docker_username}/${docker_repo}:${semver}
 }
 
 prod() {
-    [ -d "${MEDIA_SHARE_DIR}" ] || term "missing env var MEDIA_SHARE_DIR"
-    [ -d "${MEDIA_CERTS_DIR}" ] || term "missing env var MEDIA_CERTS_DIR"
-    build
-    docker stop media-share-latest > /dev/null || echo "container not running"
-    docker stop media-share-latest > /dev/null || echo "container not found"
+    [ "${MEDIA_SHARE_DIR}" = "" ] && term "missing env var MEDIA_SHARE_DIR"
+    [ -d "${MEDIA_SHARE_DIR}" ] || term "dir \"${MEDIA_SHARE_DIR}\" not found"
+    [ "${MEDIA_CERTS_DIR}" = "" ] && term "missing env var MEDIA_CERTS_DIR"
+    [ -d "${MEDIA_CERTS_DIR}" ] || term "dir \"${MEDIA_CERTS_DIR}\" not found"
 
-    docker run --name media-share --pull always --restart=always -d \
+    build
+
+    semver=latest
+    local container=${docker_repo}-${semver}
+
+    docker stop ${container} > /dev/null && docker rm ${container} > /dev/null || echo "container ${container} not running"
+    docker run --name ${docker_repo} --pull always --restart=always -d \
         -p "127.0.0.1:58080:58082" \
         -v "${MEDIA_SHARE_DIR}:/home/node/app/media" \
         -v "${MEDIA_CERTS_DIR}/cert.crt:/run/secrets/cert.crt:ro" \
         -v "${MEDIA_CERTS_DIR}/cert.key:/run/secrets/cert.key:ro" \
-        -e "AUTH_CLIENT=" `# required` \
-        -e "AUTH_EMAILS=" `# required` \
-        vallyian/media-share:latest
+        -e "AUTH_CLIENT" \
+        -e "AUTH_EMAILS" \
+        ${docker_username}/${docker_repo}:${semver}
 }
 
 case "${1}" in
