check test results
Signed-off-by: Valentin Ianchis <vallyian@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,6 +85,13 @@ jobs:
                   name: test-results
                   path: artifacts/test-results
 
+            - name: Check test results
+              run: |
+                if [ ! -f test-results/*.xml ]; then
+                   echo "test results not found"
+                   exit 1
+                fi
+
             - name: Publish Test Results
               uses: EnricoMi/publish-unit-test-result-action@2a60c5d47eb29cd5cc922f51bbea18e148f56203 # v2.0.0
               if: always()
